version: '3'

services:
  db:
    image: mysql:8.0.26
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    container_name: MySQL
    
  web:
    build: .
    image: gunicorn:tmp
    container_name: django_gunicorn
    volumes:
      - .:/code
      - gunicorn:/var/run/gunicorn
    env_file: docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
volumes:
  gunicorn:
    driver: local
