# Generated by Django 3.2.11 on 2022-06-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
    ]
