# Generated by Django 3.2.11 on 2022-08-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_category_post_categoryyyy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryyyy',
            new_name='category',
        ),
    ]
